defmodule MobAsh.Info do
  @moduledoc """
  Pure Ash-introspection helpers the generator and the shared screens build
  on. Kept public + side-effect free so the resource→UI mapping is unit-
  testable without a device (and without mob_dev).
  """

  @doc ~S(Route segment for a resource: `MyApp.Blog.Post` → `"post"`.)
  @spec route_segment(module()) :: String.t()
  def route_segment(resource) do
    resource |> Module.split() |> List.last() |> Macro.underscore()
  end

  @doc ~S(Human title for a resource: `MyApp.Blog.Post` → `"Post"`.)
  @spec title(module()) :: String.t()
  def title(resource) do
    resource |> Module.split() |> List.last()
  end

  @doc """
  Public attributes to DISPLAY, primary key + autogenerated timestamps last.
  """
  @spec display_attributes(module()) :: [atom()]
  def display_attributes(resource) do
    pk = Ash.Resource.Info.primary_key(resource)

    resource
    |> Ash.Resource.Info.public_attributes()
    |> Enum.map(& &1.name)
    |> Enum.sort_by(&(&1 in pk || &1 in [:inserted_at, :updated_at]))
  end

  @doc """
  Public, writable, non-generated attributes — what the create form edits.
  Only types a `<TextField>` can carry for now (string-castable scalars).
  """
  @spec form_attributes(module()) :: [atom()]
  def form_attributes(resource) do
    pk = Ash.Resource.Info.primary_key(resource)

    resource
    |> Ash.Resource.Info.public_attributes()
    |> Enum.filter(fn a ->
      a.writable? and not a.generated? and a.name not in pk and
        a.name not in [:inserted_at, :updated_at] and
        a.type in [Ash.Type.String, Ash.Type.CiString, Ash.Type.Integer, Ash.Type.Atom]
    end)
    |> Enum.map(& &1.name)
  end

  @doc """
  One-line label for a record row: the first non-pk display attribute's value
  (fallback: the primary key).
  """
  @spec row_label(module(), struct()) :: String.t()
  def row_label(resource, record) do
    pk = Ash.Resource.Info.primary_key(resource)

    field =
      Enum.find(display_attributes(resource), List.first(pk), &(&1 not in pk))

    record |> Map.get(field) |> to_string()
  end

  @doc "Stringified value of `field` on `record` (nil-safe)."
  @spec field_value(struct(), atom()) :: String.t()
  def field_value(record, field) do
    case Map.get(record, field) do
      nil -> ""
      %DateTime{} = dt -> DateTime.to_iso8601(dt)
      other -> to_string(other)
    end
  end
end
